import { walk } from "https://deno.land/std@0.224.0/fs/walk.ts";
import { fromFileUrl, join } from "https://deno.land/std@0.224.0/path/mod.ts";

function formatIconName(fileName: string): string {
  const cleanName = fileName.replace(".svg", "");
  const parts = cleanName.split("_");

  const variant = parts.pop();
  const size = parts.pop();

  const name = parts
    .map((part, index) => 
      index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)
    )
    .join("");

  const pascalVariant = variant!.charAt(0).toUpperCase() + variant!.slice(1);
  
  return `${name}${pascalVariant}${size}`;
}

async function buildTemplate() {
  const packageJsonUrl = import.meta.resolve("@fluentui/svg-icons/package.json");
  const packagePath = fromFileUrl(new URL(".", packageJsonUrl));
  const iconsPath = join(packagePath, "icons");

  const output: string[] = [];

  output.push(`// Autogenerated, do not edit this file manually`);
	output.push(``);

  for await (const entry of walk(iconsPath, { exts: [".svg"] })) {
		if (entry.isFile) {
			const content = await Deno.readTextFile(entry.path);
			const varName = formatIconName(entry.name);
			
			output.push(`\$${varName}: '${content}';`);
		}
	}

	output.push(``);

	return output.join("\n")
}

async function main() {
	const template = await buildTemplate();
	Deno.writeTextFile("./sass/base/_icons.scss", template)
	console.log("Done")
}

main()